### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by wallymathieu** [ozzymcduff/Cake.SemVer.FromAssembly#6]
> To avoid the duplication of the NuGet packages, can I suggest that you follow the deprecation process outlined here:
> 
> https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package
> 
> Yes, that is the process followed for Chocolatey Packages, but the same process applies equally to NuGet Packages.
> 

https://github.com/cake-build/website/pull/307#issuecomment-287583415

**Comment by gep13** [comment]
@wallymathieu I think this also makes sense for this nuget package as well, right?

https://www.nuget.org/packages/Cake.SemVer.FromBinary/

**Comment by wallymathieu** [comment]
Indeed!

**Comment by gep13** [comment]
@wallymathieu just wanted to follow up to see if this is still something that you were planning on going ahead with?  Do you need any help?

Thanks!

**Comment by wallymathieu** [comment]
If you would like to help out that would be awesome!

**Comment by gep13** [comment]
@wallymathieu I you wanted to add the cake-contrib user to the NuGet Packages on NuGet.org, I would happily go through the process of obsoleting the packages.

**Comment by wallymathieu** [comment]
I've added cake-contrib to the nuget package, if you want I can transfer this repo to somewhere else.

**Comment by wallymathieu** [comment]
I've added you as a contributor to the repository.

**Comment by gep13** [comment]
@wallymathieu can you add the same user to this NuGet Package as well:

https://www.nuget.org/packages/SemVer.FromAssembly/

That would mean that the only one that is left is this one:

https://www.nuget.org/packages/Cake.SynVer/

Which I believe is the correct one, yes?

Not sure the repository needs to be moved anywhere, as the source code is now covered elsewhere, right?  Perhaps simply a note in the project README directing people to the correct location?

**Comment by wallymathieu** [comment]
I've added you to https://github.com/wallymathieu/SemVer.FromAssembly/invitations as well

**Comment by wallymathieu** [comment]
There is already a text in the readme for SemVer.FromAssembly that it's obsolete

**Comment by gep13** [comment]
@wallymathieu while you are there...  Do you also think that is makes sense to add the cake-contrib user to the Cake.SynVer package?  We (the Cake Team) wouldn't use that to push any package versions or anything like that, it would simply provide some clarity to users of the Cake Community that Cake.SynVer was a Cake Addin.  I have been working to include this user onto all Cake Addin's that are published to NuGet.org.  That way, users can get a complete list of all addins from the cake-contrib user profile, as shown here:

https://www.nuget.org/profiles/cake-contrib

Thoughts?

**Comment by wallymathieu** [comment]
Sure! We could add the Cake team to that repository. I've added you to that one as well: https://github.com/fsprojects/Cake.SynVer/invitations

**Comment by gep13** [comment]
@wallymathieu that is great news! Thank you very much!

**Comment by wallymathieu** [comment]
I've added cake-contrib to https://www.nuget.org/packages/Cake.SemVer.FromAssembly/ as well

**Comment by gep13** [comment]
Ok, hold on, I am getting lost.... 😄 

So, to clarify, you have the following packages:

[SemVer.FromAssembly](https://www.nuget.org/packages/SemVer.FromAssembly/)
[Cake.SemVer.FromAssembly](https://www.nuget.org/packages/Cake.SemVer.FromAssembly/)
[Cake.SemVer.FromBinary](https://www.nuget.org/packages/Cake.SemVer.FromBinary/)

All of which can be deprecated.  And the only package that should remain is:

[Cake.SynVer](https://www.nuget.org/packages/Cake.SynVer/)

Is that correct?

**Comment by wallymathieu** [comment]
Exactly!

**Comment by gep13** [comment]
Okay dokay.  All the packages have been pushed, and all marked as deprecated.  Thanks again!

**Comment by wallymathieu** [comment]
Thanks again for the help @gep13 ! Much appreciated!

**Comment by gep13** [comment]
@wallymathieu you are very welcome.
